name: "BAAI BGE-M3 + Cross-encoder (MS MARCO)"
chunk_size: 400
retrieval_method: "sentence-transformers"
retrieval_kwargs:
  model_name: "BAAI/bge-m3"
reranker_method: "cross-encoder"
reranker_kwargs:
  model_name: "cross-encoder/ms-marco-MiniLM-L-2-v2"
