name: "Instruct Qwen3 + Cross-encoder (MS MARCO)"
chunk_size: 400
retrieval_method: "instruct-sentence-transformers"
retrieval_kwargs:
  model_name: "Qwen/Qwen3-Embedding-0.6B"
  instruction: "Given a document query, retrieve relevant passages that answer the query"
reranker_method: "cross-encoder"
reranker_kwargs:
  model_name: "cross-encoder/ms-marco-MiniLM-L-2-v2"