name: "Focused Qwen Scaling Study"
description: "Focused evaluation of Qwen model scaling effects for quick iteration"

# List of configuration files to evaluate
configs:
  # === CORE QWEN SCALING COMPARISON ===
  # Pure embedding scaling progression
  - st_qwen_400.yaml          # 0.6B baseline
  - st_qwen4b_400.yaml        # 4B upgrade
  - st_qwen8b_400.yaml        # 8B upgrade
  
  # Same-scale embedding + reranker pairs
  - st_qwen_400_ce_qwen.yaml       # 0.6B + 0.6B
  - st_qwen4b_400_ce_qwen4b.yaml   # 4B + 4B
  - st_qwen8b_400_ce_qwen8b.yaml   # 8B + 8B
  
  # Key processor ablations with scaling
  - st_qwen_400_docling.yaml       # 0.6B + Docling
  - st_qwen4b_400_docling.yaml     # 4B + Docling
  - st_qwen8b_400_docling.yaml     # 8B + Docling
  
  - st_qwen_400_markitdown.yaml    # 0.6B + MarkItDown
  - st_qwen4b_400_markitdown.yaml  # 4B + MarkItDown
  - st_qwen8b_400_markitdown.yaml  # 8B + MarkItDown

# Evaluation settings
settings:
  max_examples: 5  # Quick testing with subset
  output_dir: "results"
  csv_filename: "qwen_scaling_focused_evaluation.csv"
  json_filename: "qwen_scaling_focused_evaluation.json"
