name: "Snowflake Arctic Embed Large v2.0 (400 chunks)"
chunk_size: 400
retrieval_method: "sentence-transformers"
retrieval_kwargs:
  model_name: "Snowflake/snowflake-arctic-embed-l-v2.0"
reranker_method: null
