name: "ST MiniLM + Cross-encoder (MS MARCO)"
chunk_size: 400
retrieval_method: "sentence-transformers"
retrieval_kwargs:
  model_name: "all-MiniLM-L6-v2"
  top_k: 10
reranker_method: "cross-encoder"
reranker_kwargs:
  model_name: "cross-encoder/ms-marco-MiniLM-L-2-v2"
  top_k: 10