name: "SentenceTransformers Qwen3 4B (400 chunks)"
chunk_size: 400
retrieval_method: "sentence-transformers"
retrieval_kwargs:
  model_name: "Qwen/Qwen3-Embedding-4B"
  top_k: 10
reranker_method: null
