name: "ST Qwen3 (400 chunks, MarkItDown)"
chunk_size: 400
retrieval_method: "sentence-transformers"
retrieval_kwargs:
  model_name: "Qwen/Qwen3-Embedding-0.6B"
  top_k: 10
reranker_method: null
processor_class: "MarkItDownProcessor"