name: "ST Qwen3 4B + Qwen4B Reranker (Docling)"
chunk_size: 400
retrieval_method: "sentence-transformers"
retrieval_kwargs:
  model_name: "Qwen/Qwen3-Embedding-4B"
  top_k: 10
reranker_method: "qwen-reranker"
reranker_kwargs:
  model_name: "Qwen/Qwen3-Reranker-4B"
  top_k: 10
processor_class: "DoclingProcessor"
