name: "ST Qwen3 8B + Qwen8B Reranker (Docling)"
chunk_size: 400
retrieval_method: "sentence-transformers"
retrieval_kwargs:
  model_name: "Qwen/Qwen3-Embedding-8B"
  top_k: 10
reranker_method: "qwen-reranker"
reranker_kwargs:
  model_name: "Qwen/Qwen3-Reranker-8B"
  top_k: 10
processor_class: "DoclingProcessor"