name: "ST Qwen3 0.6B + Qwen4B Reranker (Mixed Scale)"
chunk_size: 400
retrieval_method: "sentence-transformers"
retrieval_kwargs:
  model_name: "Qwen/Qwen3-Embedding-0.6B"
reranker_method: "qwen-reranker"
reranker_kwargs:
  model_name: "Qwen/Qwen3-Reranker-4B"
