name: "ST Qwen3 8B + Qwen0.6B Reranker (Mixed Scale)"
chunk_size: 400
retrieval_method: "sentence-transformers"
retrieval_kwargs:
  model_name: "Qwen/Qwen3-Embedding-8B"
reranker_method: "qwen-reranker"
reranker_kwargs:
  model_name: "Qwen/Qwen3-Reranker-0.6B"
