name: "BAAI BGE-M3 (400 chunks)"
chunk_size: 400
retrieval_method: "sentence-transformers"
retrieval_kwargs:
  model_name: "BAAI/bge-m3"
  top_k: 10
reranker_method: null
processor_class: "PyPDF2Processor"