config_mapping:
  BM25 Baseline (400 chunks): "BM25 Baseline (PyPDF2)"
  BM25 + Cross-encoder (MS MARCO): "BM25 + Cross-encoder (PyPDF2)"
  BM25 Baseline (400 chunks, MarkItDown): "BM25 (MarkItDown)"
  BM25 Baseline (400 chunks, Docling): "BM25 (Docling)"
  BM25 Baseline (400 chunks, Marker): "BM25 (Marker)"
  SentenceTransformers MiniLM (400 chunks): "ST MiniLM (PyPDF2)"
  SentenceTransformers Qwen3 (400 chunks): "ST Qwen3-0.6B (PyPDF2)"
  SentenceTransformers Qwen3 (800 chunks): "ST Qwen3-0.6B (800)"
  SentenceTransformers Qwen3 (1200 chunks): "ST Qwen3-0.6B (1200)"
  SentenceTransformers Qwen3 4B (400 chunks): "ST Qwen3-4B (PyPDF2)"
  SentenceTransformers Qwen3 8B (400 chunks): "ST Qwen3-8B (PyPDF2)"
  SentenceTransformers EmbeddingGemma (400 chunks, PyPDF2): "ST EmbeddingGemma (PyPDF2)"
  SentenceTransformers EmbeddingGemma (400 chunks, Docling): "ST EmbeddingGemma (Docling)"
  ST Gemma 9B (400 chunks, Marker): "ST EmbeddingGemma (Marker)"
  Instruct Qwen3 Embedding (400 chunks): "Instruct Qwen3-0.6B (PyPDF2)"
  Instruct Qwen3 Embedding (800 chunks): "Instruct Qwen3-0.6B (800)"
  Instruct EmbeddingGemma (400 chunks): "Instruct EmbeddingGemma (PyPDF2)"
  Instruct Qwen3 + Cross-encoder (MS MARCO): "Instruct Qwen3 + Cross-encoder"
  ST MiniLM + Cross-encoder (MS MARCO): "ST MiniLM + Cross-encoder"
  ST Qwen3 + Cross-encoder (MS MARCO): "ST Qwen3 + Cross-encoder"
  ST Qwen3 + Qwen Reranker: "ST Qwen3 + Qwen Reranker (PyPDF2)"
  ST Qwen3 + Qwen Reranker (800 chunks): "ST Qwen3 + Qwen Reranker (800)"
  ST Qwen3 4B + Qwen4B Reranker: "ST Qwen3-4B + Reranker (PyPDF2)"
  ST Qwen3 8B + Qwen8B Reranker: "ST Qwen3-8B + Reranker (PyPDF2)"
  ST Qwen3 (400 chunks, MarkItDown): "ST Qwen3-0.6B (MarkItDown)"
  ST Qwen3 4B (400 chunks, MarkItDown): "ST Qwen3-4B (MarkItDown)"
  ST Qwen3 8B (400 chunks, MarkItDown): "ST Qwen3-8B (MarkItDown)"
  ST Qwen3 + Qwen Reranker (MarkItDown): "ST Qwen3 + Qwen Reranker (MarkItDown)"
  ST Qwen3 4B + Qwen4B Reranker (MarkItDown): "ST Qwen3-4B + Reranker (MarkItDown)"
  ST Qwen3 8B + Qwen8B Reranker (MarkItDown): "ST Qwen3-8B + Reranker (MarkItDown)"
  ST Qwen3 (400 chunks, Docling): "ST Qwen3-0.6B (Docling)"
  ST Qwen3 4B (400 chunks, Docling): "ST Qwen3-4B (Docling)"
  ST Qwen3 8B (400 chunks, Docling): "ST Qwen3-8B (Docling)"
  ST Qwen3 4B + Qwen4B Reranker (Docling): "ST Qwen3-4B + Reranker (Docling)"
  ST Qwen3 8B + Qwen8B Reranker (Docling): "ST Qwen3-8B + Reranker (Docling)"
  ST Qwen3 4B (400 chunks, Marker): "ST Qwen3-4B (Marker)"
  ST Qwen3 8B (400 chunks, Marker): "ST Qwen3-8B (Marker)"
  BAAI BGE-M3 (400 chunks): "BAAI BGE-M3 (PyPDF2)"
  Multilingual E5 Large (400 chunks): "Multilingual E5 Large (PyPDF2)"
  Snowflake Arctic Embed Large v2.0 (400 chunks): "Snowflake Arctic Embed v2.0 (PyPDF2)"

