config_mapping:
  "BM25 Baseline (400 chunks)": "BM25 Baseline (PyPDF2)"
  "BM25 + Cross-encoder (MS MARCO)": "BM25 + Cross-encoder (PyPDF2)"
  "SentenceTransformers MiniLM (400 chunks)": "ST MiniLM (PyPDF2)"
  "SentenceTransformers Qwen3 (400 chunks)": "ST Qwen3-0.6B (PyPDF2)"
  "SentenceTransformers Qwen3 (800 chunks)": "ST Qwen3-0.6B (800)"
  "BAAI BGE-M3 (400 chunks)": "BAAI BGE-M3 (PyPDF2)"
  "BAAI BGE-M3 + Cross-encoder (MS MARCO)": "BAAI BGE-M3 + Cross-encoder (PyPDF2)"
  "BAAI BGE-M3 + Qwen Reranker": "BAAI BGE-M3 + Qwen Reranker (PyPDF2)"
  "ST MiniLM + Cross-encoder (MS MARCO)": "ST MiniLM + Cross-encoder (PyPDF2)"
  "ST Qwen3 + Cross-encoder (MS MARCO)": "ST Qwen3 + Cross-encoder (PyPDF2)"
  "ST Qwen3 + Qwen Reranker": "ST Qwen3 + Qwen Reranker (PyPDF2)"
  "ST Qwen3 + Qwen Reranker (800 chunks)": "ST Qwen3 + Qwen Reranker (800)"
  "SentenceTransformers Qwen3 4B (400 chunks)": "ST Qwen3-4B (PyPDF2)"
  "SentenceTransformers Qwen3 8B (400 chunks)": "ST Qwen3-8B (PyPDF2)"
  "ST Qwen3 4B + Qwen4B Reranker": "ST Qwen3-4B + Reranker (PyPDF2)"
  "ST Qwen3 8B + Qwen8B Reranker": "ST Qwen3-8B + Reranker (PyPDF2)"
